Repository apel/monitoring, pull requests merged in 2024-11, with the labels that each got.

#21 Add common configuration file
  monitoring/settings.ini
  monitoring/settings.py
Labels: enhancement

#23 Update packages to work with py3.6
  docs/what_gets_installed.md
  requirements.txt
Labels: enhancement, dependencies

#22 Add styles sheets and fix references to them
  monitoring/publishing/static/style.css
  monitoring/publishing/static/stylesheet.css
  monitoring/publishing/templates/gridsites.html
  monitoring/publishing/templates/gridsync.html
  monitoring/publishing/templates/gridsync_singlesite.html
  monitoring/publishing/templates/gridsync_submithost.html
Labels: bug

#24 Add pre-commit config and tidy up
  .pre-commit-config.yaml
  docs/what_gets_installed.md
  monitoring/availability/templates/status.html
  monitoring/publishing/static/style.css
  monitoring/publishing/static/stylesheet.css
  monitoring/publishing/templates/gridsites.html
  monitoring/publishing/templates/gridsync.html
  monitoring/publishing/templates/gridsync_singlesite.html
  monitoring/publishing/templates/gridsync_submithost.html
Labels: enhancement
